package gocountrydetect

var langs map[string]Countries = map[string]Countries{
	"en": Countries{
		Country{code: "AFG", name: "Afghanistan"},
		Country{code: "ALA", name: "Åland Islands"},
		Country{code: "ALB", name: "Albania"},
		Country{code: "DZA", name: "Algeria"},
		Country{code: "ASM", name: "American Samoa"},
		Country{code: "AND", name: "Andorra"},
		Country{code: "AGO", name: "Angola"},
		Country{code: "AIA", name: "Anguilla"},
		Country{code: "ATA", name: "Antarctica"},
		Country{code: "ATG", name: "Antigua and Barbuda"},
		Country{code: "ARG", name: "Argentina"},
		Country{code: "ARM", name: "Armenia"},
		Country{code: "ABW", name: "Aruba"},
		Country{code: "AUS", name: "Australia"},
		Country{code: "AUT", name: "Austria"},
		Country{code: "AZE", name: "Azerbaijan"},
		Country{code: "BHS", name: "Bahamas"},
		Country{code: "BHR", name: "Bahrain"},
		Country{code: "BGD", name: "Bangladesh"},
		Country{code: "BRB", name: "Barbados"},
		Country{code: "BLR", name: "Belarus"},
		Country{code: "BEL", name: "Belgium"},
		Country{code: "BLZ", name: "Belize"},
		Country{code: "BEN", name: "Benin"},
		Country{code: "BMU", name: "Bermuda"},
		Country{code: "BTN", name: "Bhutan"},
		Country{code: "BOL", name: "Bolivia (Plurinational State of)"},
		Country{code: "BES", name: "Bonaire, Sint Eustatius and Saba"},
		Country{code: "BIH", name: "Bosnia and Herzegovina"},
		Country{code: "BWA", name: "Botswana"},
		Country{code: "BVT", name: "Bouvet Island"},
		Country{code: "BRA", name: "Brazil"},
		Country{code: "IOT", name: "British Indian Ocean Territory"},
		Country{code: "UMI", name: "United States Minor Outlying Islands"},
		Country{code: "VGB", name: "Virgin Islands (British)"},
		Country{code: "VIR", name: "Virgin Islands (U.S.)"},
		Country{code: "BRN", name: "Brunei Darussalam"},
		Country{code: "BGR", name: "Bulgaria"},
		Country{code: "BFA", name: "Burkina Faso"},
		Country{code: "BDI", name: "Burundi"},
		Country{code: "KHM", name: "Cambodia"},
		Country{code: "CMR", name: "Cameroon"},
		Country{code: "CAN", name: "Canada"},
		Country{code: "CPV", name: "Cabo Verde"},
		Country{code: "CYM", name: "Cayman Islands"},
		Country{code: "CAF", name: "Central African Republic"},
		Country{code: "TCD", name: "Chad"},
		Country{code: "CHL", name: "Chile"},
		Country{code: "CHN", name: "China"},
		Country{code: "CXR", name: "Christmas Island"},
		Country{code: "CCK", name: "Cocos (Keeling) Islands"},
		Country{code: "COL", name: "Colombia"},
		Country{code: "COM", name: "Comoros"},
		Country{code: "COG", name: "Congo"},
		Country{code: "COD", name: "Congo (Democratic Republic of the)"},
		Country{code: "COK", name: "Cook Islands"},
		Country{code: "CRI", name: "Costa Rica"},
		Country{code: "HRV", name: "Croatia"},
		Country{code: "CUB", name: "Cuba"},
		Country{code: "CUW", name: "Curaçao"},
		Country{code: "CYP", name: "Cyprus"},
		Country{code: "CZE", name: "Czech Republic"},
		Country{code: "DNK", name: "Denmark"},
		Country{code: "DJI", name: "Djibouti"},
		Country{code: "DMA", name: "Dominica"},
		Country{code: "DOM", name: "Dominican Republic"},
		Country{code: "ECU", name: "Ecuador"},
		Country{code: "EGY", name: "Egypt"},
		Country{code: "SLV", name: "El Salvador"},
		Country{code: "GNQ", name: "Equatorial Guinea"},
		Country{code: "ERI", name: "Eritrea"},
		Country{code: "EST", name: "Estonia"},
		Country{code: "ETH", name: "Ethiopia"},
		Country{code: "FLK", name: "Falkland Islands (Malvinas)"},
		Country{code: "FRO", name: "Faroe Islands"},
		Country{code: "FJI", name: "Fiji"},
		Country{code: "FIN", name: "Finland"},
		Country{code: "FRA", name: "France"},
		Country{code: "GUF", name: "French Guiana"},
		Country{code: "PYF", name: "French Polynesia"},
		Country{code: "ATF", name: "French Southern Territories"},
		Country{code: "GAB", name: "Gabon"},
		Country{code: "GMB", name: "Gambia"},
		Country{code: "GEO", name: "Georgia"},
		Country{code: "DEU", name: "Germany"},
		Country{code: "GHA", name: "Ghana"},
		Country{code: "GIB", name: "Gibraltar"},
		Country{code: "GRC", name: "Greece"},
		Country{code: "GRL", name: "Greenland"},
		Country{code: "GRD", name: "Grenada"},
		Country{code: "GLP", name: "Guadeloupe"},
		Country{code: "GUM", name: "Guam"},
		Country{code: "GTM", name: "Guatemala"},
		Country{code: "GGY", name: "Guernsey"},
		Country{code: "GIN", name: "Guinea"},
		Country{code: "GNB", name: "Guinea-Bissau"},
		Country{code: "GUY", name: "Guyana"},
		Country{code: "HTI", name: "Haiti"},
		Country{code: "HMD", name: "Heard Island and McDonald Islands"},
		Country{code: "VAT", name: "Holy See"},
		Country{code: "HND", name: "Honduras"},
		Country{code: "HKG", name: "Hong Kong"},
		Country{code: "HUN", name: "Hungary"},
		Country{code: "ISL", name: "Iceland"},
		Country{code: "IND", name: "India"},
		Country{code: "IDN", name: "Indonesia"},
		Country{code: "CIV", name: "Côte d'Ivoire"},
		Country{code: "IRN", name: "Iran (Islamic Republic of)"},
		Country{code: "IRQ", name: "Iraq"},
		Country{code: "IRL", name: "Ireland"},
		Country{code: "IMN", name: "Isle of Man"},
		Country{code: "ISR", name: "Israel"},
		Country{code: "ITA", name: "Italy"},
		Country{code: "JAM", name: "Jamaica"},
		Country{code: "JPN", name: "Japan"},
		Country{code: "JEY", name: "Jersey"},
		Country{code: "JOR", name: "Jordan"},
		Country{code: "KAZ", name: "Kazakhstan"},
		Country{code: "KEN", name: "Kenya"},
		Country{code: "KIR", name: "Kiribati"},
		Country{code: "KWT", name: "Kuwait"},
		Country{code: "KGZ", name: "Kyrgyzstan"},
		Country{code: "LAO", name: "Lao People's Democratic Republic"},
		Country{code: "LVA", name: "Latvia"},
		Country{code: "LBN", name: "Lebanon"},
		Country{code: "LSO", name: "Lesotho"},
		Country{code: "LBR", name: "Liberia"},
		Country{code: "LBY", name: "Libya"},
		Country{code: "LIE", name: "Liechtenstein"},
		Country{code: "LTU", name: "Lithuania"},
		Country{code: "LUX", name: "Luxembourg"},
		Country{code: "MAC", name: "Macao"},
		Country{code: "MKD", name: "Macedonia (the former Yugoslav Republic of)"},
		Country{code: "MDG", name: "Madagascar"},
		Country{code: "MWI", name: "Malawi"},
		Country{code: "MYS", name: "Malaysia"},
		Country{code: "MDV", name: "Maldives"},
		Country{code: "MLI", name: "Mali"},
		Country{code: "MLT", name: "Malta"},
		Country{code: "MHL", name: "Marshall Islands"},
		Country{code: "MTQ", name: "Martinique"},
		Country{code: "MRT", name: "Mauritania"},
		Country{code: "MUS", name: "Mauritius"},
		Country{code: "MYT", name: "Mayotte"},
		Country{code: "MEX", name: "Mexico"},
		Country{code: "FSM", name: "Micronesia (Federated States of)"},
		Country{code: "MDA", name: "Moldova (Republic of)"},
		Country{code: "MCO", name: "Monaco"},
		Country{code: "MNG", name: "Mongolia"},
		Country{code: "MNE", name: "Montenegro"},
		Country{code: "MSR", name: "Montserrat"},
		Country{code: "MAR", name: "Morocco"},
		Country{code: "MOZ", name: "Mozambique"},
		Country{code: "MMR", name: "Myanmar"},
		Country{code: "NAM", name: "Namibia"},
		Country{code: "NRU", name: "Nauru"},
		Country{code: "NPL", name: "Nepal"},
		Country{code: "NLD", name: "Netherlands"},
		Country{code: "NCL", name: "New Caledonia"},
		Country{code: "NZL", name: "New Zealand"},
		Country{code: "NIC", name: "Nicaragua"},
		Country{code: "NER", name: "Niger"},
		Country{code: "NGA", name: "Nigeria"},
		Country{code: "NIU", name: "Niue"},
		Country{code: "NFK", name: "Norfolk Island"},
		Country{code: "PRK", name: "Korea (Democratic People's Republic of)"},
		Country{code: "MNP", name: "Northern Mariana Islands"},
		Country{code: "NOR", name: "Norway"},
		Country{code: "OMN", name: "Oman"},
		Country{code: "PAK", name: "Pakistan"},
		Country{code: "PLW", name: "Palau"},
		Country{code: "PSE", name: "Palestine, State of"},
		Country{code: "PAN", name: "Panama"},
		Country{code: "PNG", name: "Papua New Guinea"},
		Country{code: "PRY", name: "Paraguay"},
		Country{code: "PER", name: "Peru"},
		Country{code: "PHL", name: "Philippines"},
		Country{code: "PCN", name: "Pitcairn"},
		Country{code: "POL", name: "Poland"},
		Country{code: "PRT", name: "Portugal"},
		Country{code: "PRI", name: "Puerto Rico"},
		Country{code: "QAT", name: "Qatar"},
		Country{code: "KOS", name: "Republic of Kosovo"},
		Country{code: "REU", name: "Réunion"},
		Country{code: "ROU", name: "Romania"},
		Country{code: "RUS", name: "Russian Federation"},
		Country{code: "RWA", name: "Rwanda"},
		Country{code: "BLM", name: "Saint Barthélemy"},
		Country{code: "SHN", name: "Saint Helena, Ascension and Tristan da Cunha"},
		Country{code: "KNA", name: "Saint Kitts and Nevis"},
		Country{code: "LCA", name: "Saint Lucia"},
		Country{code: "MAF", name: "Saint Martin (French part)"},
		Country{code: "SPM", name: "Saint Pierre and Miquelon"},
		Country{code: "VCT", name: "Saint Vincent and the Grenadines"},
		Country{code: "WSM", name: "Samoa"},
		Country{code: "SMR", name: "San Marino"},
		Country{code: "STP", name: "Sao Tome and Principe"},
		Country{code: "SAU", name: "Saudi Arabia"},
		Country{code: "SEN", name: "Senegal"},
		Country{code: "SRB", name: "Serbia"},
		Country{code: "SYC", name: "Seychelles"},
		Country{code: "SLE", name: "Sierra Leone"},
		Country{code: "SGP", name: "Singapore"},
		Country{code: "SXM", name: "Sint Maarten (Dutch part)"},
		Country{code: "SVK", name: "Slovakia"},
		Country{code: "SVN", name: "Slovenia"},
		Country{code: "SLB", name: "Solomon Islands"},
		Country{code: "SOM", name: "Somalia"},
		Country{code: "ZAF", name: "South Africa"},
		Country{code: "SGS", name: "South Georgia and the South Sandwich Islands"},
		Country{code: "KOR", name: "Korea (Republic of)"},
		Country{code: "SSD", name: "South Sudan"},
		Country{code: "ESP", name: "Spain"},
		Country{code: "LKA", name: "Sri Lanka"},
		Country{code: "SDN", name: "Sudan"},
		Country{code: "SUR", name: "Suriname"},
		Country{code: "SJM", name: "Svalbard and Jan Mayen"},
		Country{code: "SWZ", name: "Swaziland"},
		Country{code: "SWE", name: "Sweden"},
		Country{code: "CHE", name: "Switzerland"},
		Country{code: "SYR", name: "Syrian Arab Republic"},
		Country{code: "TWN", name: "Taiwan"},
		Country{code: "TJK", name: "Tajikistan"},
		Country{code: "TZA", name: "Tanzania, United Republic of"},
		Country{code: "THA", name: "Thailand"},
		Country{code: "TLS", name: "Timor-Leste"},
		Country{code: "TGO", name: "Togo"},
		Country{code: "TKL", name: "Tokelau"},
		Country{code: "TON", name: "Tonga"},
		Country{code: "TTO", name: "Trinidad and Tobago"},
		Country{code: "TUN", name: "Tunisia"},
		Country{code: "TUR", name: "Turkey"},
		Country{code: "TKM", name: "Turkmenistan"},
		Country{code: "TCA", name: "Turks and Caicos Islands"},
		Country{code: "TUV", name: "Tuvalu"},
		Country{code: "UGA", name: "Uganda"},
		Country{code: "UKR", name: "Ukraine"},
		Country{code: "ARE", name: "United Arab Emirates"},
		Country{code: "GBR", name: "United Kingdom of Great Britain and Northern Ireland"},
		Country{code: "USA", name: "United States of America"},
		Country{code: "URY", name: "Uruguay"},
		Country{code: "UZB", name: "Uzbekistan"},
		Country{code: "VUT", name: "Vanuatu"},
		Country{code: "VEN", name: "Venezuela (Bolivarian Republic of)"},
		Country{code: "VNM", name: "Viet Nam"},
		Country{code: "WLF", name: "Wallis and Futuna"},
		Country{code: "ESH", name: "Western Sahara"},
		Country{code: "YEM", name: "Yemen"},
		Country{code: "ZMB", name: "Zambia"},
		Country{code: "ZWE", name: "Zimbabwe"},
	},
	"es": Countries{
		Country{code: "AFG", name: "Afganistán"},
		Country{code: "ALA", name: "Alandia"},
		Country{code: "ALB", name: "Albania"},
		Country{code: "DZA", name: "Argelia"},
		Country{code: "ASM", name: "Samoa Americana"},
		Country{code: "AND", name: "Andorra"},
		Country{code: "AGO", name: "Angola"},
		Country{code: "AIA", name: "Anguilla"},
		Country{code: "ATA", name: "Antártida"},
		Country{code: "ATG", name: "Antigua y Barbuda"},
		Country{code: "ARG", name: "Argentina"},
		Country{code: "ARM", name: "Armenia"},
		Country{code: "ABW", name: "Aruba"},
		Country{code: "AUS", name: "Australia"},
		Country{code: "AUT", name: "Austria"},
		Country{code: "AZE", name: "Azerbaiyán"},
		Country{code: "BHS", name: "Bahamas"},
		Country{code: "BHR", name: "Bahrein"},
		Country{code: "BGD", name: "Bangladesh"},
		Country{code: "BRB", name: "Barbados"},
		Country{code: "BLR", name: "Bielorrusia"},
		Country{code: "BEL", name: "Bélgica"},
		Country{code: "BLZ", name: "Belice"},
		Country{code: "BEN", name: "Benín"},
		Country{code: "BMU", name: "Bermudas"},
		Country{code: "BTN", name: "Bután"},
		Country{code: "BOL", name: "Bolivia"},
		Country{code: "BIH", name: "Bosnia y Herzegovina"},
		Country{code: "BWA", name: "Botswana"},
		Country{code: "BVT", name: "Isla Bouvet"},
		Country{code: "BRA", name: "Brasil"},
		Country{code: "IOT", name: "Territorio Británico del Océano \u00cdndico"},
		Country{code: "UMI", name: "Islas Ultramarinas Menores de Estados Unidos"},
		Country{code: "VGB", name: "Islas Vírgenes del Reino Unido"},
		Country{code: "VIR", name: "Islas Vírgenes de los Estados Unidos"},
		Country{code: "BRN", name: "Brunei"},
		Country{code: "BGR", name: "Bulgaria"},
		Country{code: "BFA", name: "Burkina Faso"},
		Country{code: "BDI", name: "Burundi"},
		Country{code: "KHM", name: "Camboya"},
		Country{code: "CMR", name: "Camerún"},
		Country{code: "CAN", name: "Canadá"},
		Country{code: "CPV", name: "Cabo Verde"},
		Country{code: "CYM", name: "Islas Caimán"},
		Country{code: "CAF", name: "República Centroafricana"},
		Country{code: "TCD", name: "Chad"},
		Country{code: "CHL", name: "Chile"},
		Country{code: "CHN", name: "China"},
		Country{code: "CXR", name: "Isla de Navidad"},
		Country{code: "CCK", name: "Islas Cocos o Islas Keeling"},
		Country{code: "COL", name: "Colombia"},
		Country{code: "COM", name: "Comoras"},
		Country{code: "COG", name: "Congo"},
		Country{code: "COD", name: "Congo (Rep. Dem.)"},
		Country{code: "COK", name: "Islas Cook"},
		Country{code: "CRI", name: "Costa Rica"},
		Country{code: "HRV", name: "Croacia"},
		Country{code: "CUB", name: "Cuba"},
		Country{code: "CYP", name: "Chipre"},
		Country{code: "CZE", name: "República Checa"},
		Country{code: "DNK", name: "Dinamarca"},
		Country{code: "DJI", name: "Yibuti"},
		Country{code: "DMA", name: "Dominica"},
		Country{code: "DOM", name: "República Dominicana"},
		Country{code: "ECU", name: "Ecuador"},
		Country{code: "EGY", name: "Egipto"},
		Country{code: "SLV", name: "El Salvador"},
		Country{code: "GNQ", name: "Guinea Ecuatorial"},
		Country{code: "ERI", name: "Eritrea"},
		Country{code: "EST", name: "Estonia"},
		Country{code: "ETH", name: "Etiopía"},
		Country{code: "FLK", name: "Islas Malvinas"},
		Country{code: "FRO", name: "Islas Faroe"},
		Country{code: "FJI", name: "Fiyi"},
		Country{code: "FIN", name: "Finlandia"},
		Country{code: "FRA", name: "Francia"},
		Country{code: "GUF", name: "Guayana Francesa"},
		Country{code: "PYF", name: "Polinesia Francesa"},
		Country{code: "ATF", name: "Tierras Australes y Antárticas Francesas"},
		Country{code: "GAB", name: "Gabón"},
		Country{code: "GMB", name: "Gambia"},
		Country{code: "GEO", name: "Georgia"},
		Country{code: "DEU", name: "Alemania"},
		Country{code: "GHA", name: "Ghana"},
		Country{code: "GIB", name: "Gibraltar"},
		Country{code: "GRC", name: "Grecia"},
		Country{code: "GRL", name: "Groenlandia"},
		Country{code: "GRD", name: "Grenada"},
		Country{code: "GLP", name: "Guadalupe"},
		Country{code: "GUM", name: "Guam"},
		Country{code: "GTM", name: "Guatemala"},
		Country{code: "GGY", name: "Guernsey"},
		Country{code: "GIN", name: "Guinea"},
		Country{code: "GNB", name: "Guinea-Bisáu"},
		Country{code: "GUY", name: "Guyana"},
		Country{code: "HTI", name: "Haiti"},
		Country{code: "HMD", name: "Islas Heard y McDonald"},
		Country{code: "VAT", name: "Santa Sede"},
		Country{code: "HND", name: "Honduras"},
		Country{code: "HKG", name: "Hong Kong"},
		Country{code: "HUN", name: "Hungría"},
		Country{code: "ISL", name: "Islandia"},
		Country{code: "IND", name: "India"},
		Country{code: "IDN", name: "Indonesia"},
		Country{code: "CIV", name: "Costa de Marfil"},
		Country{code: "IRN", name: "Iran"},
		Country{code: "IRQ", name: "Irak"},
		Country{code: "IRL", name: "Irlanda"},
		Country{code: "IMN", name: "Isla de Man"},
		Country{code: "ISR", name: "Israel"},
		Country{code: "ITA", name: "Italia"},
		Country{code: "JAM", name: "Jamaica"},
		Country{code: "JPN", name: "Japón"},
		Country{code: "JEY", name: "Jersey"},
		Country{code: "JOR", name: "Jordania"},
		Country{code: "KAZ", name: "Kazajistán"},
		Country{code: "KEN", name: "Kenia"},
		Country{code: "KIR", name: "Kiribati"},
		Country{code: "KWT", name: "Kuwait"},
		Country{code: "KGZ", name: "Kirguizistán"},
		Country{code: "LAO", name: "Laos"},
		Country{code: "LVA", name: "Letonia"},
		Country{code: "LBN", name: "Líbano"},
		Country{code: "LSO", name: "Lesotho"},
		Country{code: "LBR", name: "Liberia"},
		Country{code: "LBY", name: "Libia"},
		Country{code: "LIE", name: "Liechtenstein"},
		Country{code: "LTU", name: "Lituania"},
		Country{code: "LUX", name: "Luxemburgo"},
		Country{code: "MAC", name: "Macao"},
		Country{code: "MKD", name: "Macedonia"},
		Country{code: "MDG", name: "Madagascar"},
		Country{code: "MWI", name: "Malawi"},
		Country{code: "MYS", name: "Malasia"},
		Country{code: "MDV", name: "Maldivas"},
		Country{code: "MLI", name: "Mali"},
		Country{code: "MLT", name: "Malta"},
		Country{code: "MHL", name: "Islas Marshall"},
		Country{code: "MTQ", name: "Martinica"},
		Country{code: "MRT", name: "Mauritania"},
		Country{code: "MUS", name: "Mauricio"},
		Country{code: "MYT", name: "Mayotte"},
		Country{code: "MEX", name: "México"},
		Country{code: "FSM", name: "Micronesia"},
		Country{code: "MDA", name: "Moldavia"},
		Country{code: "MCO", name: "Mónaco"},
		Country{code: "MNG", name: "Mongolia"},
		Country{code: "MNE", name: "Montenegro"},
		Country{code: "MSR", name: "Montserrat"},
		Country{code: "MAR", name: "Marruecos"},
		Country{code: "MOZ", name: "Mozambique"},
		Country{code: "MMR", name: "Myanmar"},
		Country{code: "NAM", name: "Namibia"},
		Country{code: "NRU", name: "Nauru"},
		Country{code: "NPL", name: "Nepal"},
		Country{code: "NLD", name: "Países Bajos"},
		Country{code: "NCL", name: "Nueva Caledonia"},
		Country{code: "NZL", name: "Nueva Zelanda"},
		Country{code: "NIC", name: "Nicaragua"},
		Country{code: "NER", name: "Níger"},
		Country{code: "NGA", name: "Nigeria"},
		Country{code: "NIU", name: "Niue"},
		Country{code: "NFK", name: "Isla de Norfolk"},
		Country{code: "PRK", name: "Corea del Norte"},
		Country{code: "MNP", name: "Islas Marianas del Norte"},
		Country{code: "NOR", name: "Noruega"},
		Country{code: "OMN", name: "Omán"},
		Country{code: "PAK", name: "Pakistán"},
		Country{code: "PLW", name: "Palau"},
		Country{code: "PSE", name: "Palestina"},
		Country{code: "PAN", name: "Panamá"},
		Country{code: "PNG", name: "Papúa Nueva Guinea"},
		Country{code: "PRY", name: "Paraguay"},
		Country{code: "PER", name: "Perú"},
		Country{code: "PHL", name: "Filipinas"},
		Country{code: "PCN", name: "Islas Pitcairn"},
		Country{code: "POL", name: "Polonia"},
		Country{code: "PRT", name: "Portugal"},
		Country{code: "PRI", name: "Puerto Rico"},
		Country{code: "QAT", name: "Catar"},
		Country{code: "KOS", name: "Kosovo"},
		Country{code: "REU", name: "Reunión"},
		Country{code: "ROU", name: "Rumania"},
		Country{code: "RUS", name: "Rusia"},
		Country{code: "RWA", name: "Ruanda"},
		Country{code: "BLM", name: "San Bartolomé"},
		Country{code: "SHN", name: "Santa Helena"},
		Country{code: "KNA", name: "San Cristóbal y Nieves"},
		Country{code: "LCA", name: "Santa Lucía"},
		Country{code: "MAF", name: "Saint Martin"},
		Country{code: "SPM", name: "San Pedro y Miquelón"},
		Country{code: "VCT", name: "San Vicente y Granadinas"},
		Country{code: "WSM", name: "Samoa"},
		Country{code: "SMR", name: "San Marino"},
		Country{code: "STP", name: "Santo Tomé y Príncipe"},
		Country{code: "SAU", name: "Arabia Saudí"},
		Country{code: "SEN", name: "Senegal"},
		Country{code: "SRB", name: "Serbia"},
		Country{code: "SYC", name: "Seychelles"},
		Country{code: "SLE", name: "Sierra Leone"},
		Country{code: "SGP", name: "Singapur"},
		Country{code: "SVK", name: "República Eslovaca"},
		Country{code: "SVN", name: "Eslovenia"},
		Country{code: "SLB", name: "Islas Salomón"},
		Country{code: "SOM", name: "Somalia"},
		Country{code: "ZAF", name: "República de Sudáfrica"},
		Country{code: "SGS", name: "Islas Georgias del Sur y Sandwich del Sur"},
		Country{code: "KOR", name: "Corea del Sur"},
		Country{code: "SSD", name: "Sudán del Sur"},
		Country{code: "ESP", name: "Espa\u00f1a"},
		Country{code: "LKA", name: "Sri Lanka"},
		Country{code: "SDN", name: "Sudán"},
		Country{code: "SUR", name: "Surinam"},
		Country{code: "SJM", name: "Islas Svalbard y Jan Mayen"},
		Country{code: "SWZ", name: "Suazilandia"},
		Country{code: "SWE", name: "Suecia"},
		Country{code: "CHE", name: "Suiza"},
		Country{code: "SYR", name: "Siria"},
		Country{code: "TWN", name: "Taiwán"},
		Country{code: "TJK", name: "Tayikistán"},
		Country{code: "TZA", name: "Tanzania"},
		Country{code: "THA", name: "Tailandia"},
		Country{code: "TLS", name: "Timor Oriental"},
		Country{code: "TGO", name: "Togo"},
		Country{code: "TKL", name: "Islas Tokelau"},
		Country{code: "TON", name: "Tonga"},
		Country{code: "TTO", name: "Trinidad y Tobago"},
		Country{code: "TUN", name: "Túnez"},
		Country{code: "TUR", name: "Turquía"},
		Country{code: "TKM", name: "Turkmenistán"},
		Country{code: "TCA", name: "Islas Turks y Caicos"},
		Country{code: "TUV", name: "Tuvalu"},
		Country{code: "UGA", name: "Uganda"},
		Country{code: "UKR", name: "Ucrania"},
		Country{code: "ARE", name: "Emiratos \u00c1rabes Unidos"},
		Country{code: "GBR", name: "Reino Unido"},
		Country{code: "USA", name: "Estados Unidos"},
		Country{code: "URY", name: "Uruguay"},
		Country{code: "UZB", name: "Uzbekistán"},
		Country{code: "VUT", name: "Vanuatu"},
		Country{code: "VEN", name: "Venezuela"},
		Country{code: "VNM", name: "Vietnam"},
		Country{code: "WLF", name: "Wallis y Futuna"},
		Country{code: "ESH", name: "Sahara Occidental"},
		Country{code: "YEM", name: "Yemen"},
		Country{code: "ZMB", name: "Zambia"},
		Country{code: "ZWE", name: "Zimbabue"},
	},
}

func getCountries(lang string) Countries {
	for k, l := range langs	{
		if k == lang {
			return l
		}
	}

	return nil
}